on:
 workflow_dispatch:
jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-20.04
    steps:
    - name: Install call
      run: |
        sudo apt update
        sudo apt install -y util-linux
    - name: Run Cal
      run: echo "hello world"
    - name: run script
      working-directory: src/webclient
      run: bash ./script.sh
#     - name: run script
#       run: bash ./script.sh

